### ISSUE TITLE
Possible to use Jacob without Node.js?

### ISSUE THREAD

**Issue by gitmh** [Canna71/Jacob#3]
I'm working on a single page web app where I would love to include Jacob as a client side service. The current code contains a lot of requires (node includes). I do not require filesystem - just generating compilers/interpreters from grammar strings on the fly. Is this technical possible or is this waste of time if I try to delete all node.js dependencies?

**Comment by Canna71** [comment]
Hi, you should have no problems using jacob on the browser. Look in the
test folder, you'll find some tests running in the browser.
The requirement on the file system is just for the command line utility,
all core modules (parser, lexer and stringreader) are designed to be used
in the browser as they are, simply include them in the correct order.


On Sat, May 2, 2015 at 10:25 PM, gitmh <notifications@github.com> wrote:

> I'm working on a single page web app where I would love to include Jacob
> as a client side service. The current code contains a lot of requires (node
> includes). I do not require filesystem - just generating
> compilers/interpreters from grammar strings on the fly. Is this technical
> possible or is this waste of time if I try to delete all node.js
> dependencies?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Canna71/Jacob/issues/3>.
>



-- 
Gabriele Cannata
