### ISSUE TITLE
Lexer issue

### ISSUE THREAD

**Issue by garronej** [Canna71/Jacob#4]
Hi,
I spoted a bug in the Lexer:

This example expose the issue: 

If we have those tree rules:

```
<> abc {console.log(`abc = ${this.jjtext}`);}
<> a {console.log(`a = ${this.jjtext}`);}
<> b {console.log(`b = ${this.jjtext}`);}
```

And we set the input : `"abcab"`

We expect to get:

abc = abc
a = a
b = b

But we get:

abc = abc
a = ab

Jacob is, in my oppignion, the best parser generator avalible for the platform if this bug could be fixed it would be awesome.

Cheers

**Comment by Canna71** [comment]
Hi, which version of Jacob are you using? I believe that bug was fixed some time ago. 
Thank you very much.

**Comment by garronej** [comment]
I am using Jacob a lot, this fix will make my life easyer.
I was using 1.0.3 witch I beleve was the last avalible on the public repo.
If I understand well you commited the fixes long time ago but they wheren't pushed.

Anyway thank you verry mutch!
